baseURL: https://robert-walser.netlify.app/
title: Balade Robert Walser

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

languages:
  de:
    contentDir: content/de
    title: Robert Walser in Biel
    languageName: Deutsch ğŸ‡©ğŸ‡ª
    weight: 1
    params:
      footer: |
        Robbie kommt zurÃ¼ck in Biou.
  fr:
    contentDir: content/fr
    title: Robert Walser Ã  Bienne
    languageName: FranÃ§ais ğŸ‡«ğŸ‡·
    weight: 2
    params:
      footer: |
        Relancer la balade RW Ã  Bienne.

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap
  - robotsTXT
  - 404

markup:
  goldmark:
    renderer:
      unsafe: true
